// <auto-generated />
using CineVerse.api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineVerse.api.Migrations
{
    [DbContext(typeof(CineverseDb))]
    [Migration("20250427100041_CreateGenres")]
    partial class CreateGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineVerse.api.Models.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 28,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 10751,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 36,
                            Name = "History"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10402,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 9648,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 10749,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 878,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 10770,
                            Name = "TV Movie"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 10752,
                            Name = "War"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Western"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
